"""菜品库 —— **自动生成，不要手改**。

由 `tools/build-dish-library.py` 从 `backend/data/dish-manifest.csv` 生成。

要改菜品：改 CSV，再跑一次生成脚本。

## 结构

- `DISH_NAMES`：菜名 -> 图片 key（key 是英文名的 slug，也是图片文件名）
- `DISH_CATEGORIES`：菜名 -> 分类（家常热菜 / 汤羹 / 凉菜 / 主食 / 早餐 / 小吃点心）
- `DISH_INGREDIENTS`：菜名 -> (必需食材 key 元组, 可选食材 key 元组)
- `BY_REQUIRED`：食材 key -> **必需**它的菜名元组
- `BY_ANY`：食材 key -> 用到它的菜名元组（必需 + 可选）

## 为什么必需和可选要分开建索引

推荐时用的是 `BY_REQUIRED`。如果两者混在一起，「蒜」「葱」「酱油」
这些调味料会出现几十次 —— 用户冰箱里有蒜，就以为能做 36 道菜，
结果点进去发现什么都缺。**必需食材才算「能做」。**

`BY_ANY` 留给「搜索」用：用户搜「鸡蛋」，应该能搜到所有用到鸡蛋的菜，
不管鸡蛋是主料还是配料。
"""
from __future__ import annotations

DISH_NAMES: dict[str, str] = {
    "西红柿炒鸡蛋": 'scrambled-eggs-with-tomatoes',
    "韭菜炒鸡蛋": 'scrambled-eggs-with-chinese-chives',
    "洋葱炒鸡蛋": 'scrambled-eggs-with-onions',
    "苦瓜炒鸡蛋": 'scrambled-eggs-with-bitter-melon',
    "黄瓜炒鸡蛋": 'scrambled-eggs-with-cucumber',
    "木耳炒鸡蛋": 'scrambled-eggs-with-wood-ear-mushrooms',
    "青椒炒鸡蛋": 'scrambled-eggs-with-green-peppers',
    "蒸蛋羹": 'steamed-egg-custard',
    "虎皮鸡蛋": 'deep-fried-eggs-in-soy-sauce-glaze',
    "木须肉": 'sauteed-pork-with-egg-and-wood-ear',
    "红烧肉": 'braised-pork-belly-in-dark-soy-sauce',
    "回锅肉": 'twice-cooked-pork-with-green-peppers',
    "青椒炒肉丝": 'shredded-pork-with-green-peppers',
    "鱼香肉丝": 'shredded-pork-in-garlic-sauce',
    "糖醋里脊": 'sweet-and-sour-pork-tenderloin',
    "京酱肉丝": 'shredded-pork-with-sweet-bean-sauce',
    "梅菜扣肉": 'steamed-pork-belly-with-preserved-mustard-greens',
    "蒜泥白肉": 'sliced-pork-belly-with-garlic-sauce',
    "粉蒸肉": 'steamed-pork-belly-with-rice-flour',
    "红烧排骨": 'braised-pork-ribs',
    "糖醋排骨": 'sweet-and-sour-pork-ribs',
    "肉末茄子": 'braised-eggplant-with-minced-pork',
    "肉末豆腐": 'braised-tofu-with-minced-pork',
    "蚂蚁上树": 'vermicelli-with-minced-pork',
    "猪肉炖粉条": 'braised-pork-with-glass-noodles',
    "白菜炖粉条": 'braised-napa-cabbage-with-glass-noodles',
    "狮子头": 'braised-pork-meatballs',
    "芹菜炒肉": 'stir-fried-pork-with-celery',
    "蒜薹炒肉": 'stir-fried-pork-with-garlic-shoots',
    "土豆炖肉": 'braised-pork-with-potatoes',
    "西红柿牛腩": 'tomato-beef-brisket-stew',
    "土豆炖牛肉": 'beef-and-potato-stew',
    "黑椒牛柳": 'black-pepper-beef-stir-fry',
    "蚝油牛肉": 'beef-in-oyster-sauce',
    "水煮牛肉": 'poached-sliced-beef-in-chili-oil',
    "小炒黄牛肉": 'hunan-style-stir-fried-beef-with-chili',
    "孜然牛肉": 'cumin-beef-stir-fry',
    "洋葱炒牛肉": 'stir-fried-beef-with-onions',
    "葱爆羊肉": 'scallion-stir-fried-lamb',
    "孜然羊肉": 'cumin-lamb-stir-fry',
    "白萝卜炖羊肉": 'braised-lamb-with-radish',
    "宫保鸡丁": 'kung-pao-chicken-with-peanuts',
    "辣子鸡": 'chongqing-spicy-chicken',
    "黄焖鸡": 'braised-chicken-with-mushrooms',
    "大盘鸡": 'xinjiang-big-plate-chicken',
    "三杯鸡": 'three-cup-chicken',
    "可乐鸡翅": 'coca-cola-chicken-wings',
    "白切鸡": 'cantonese-poached-chicken',
    "口水鸡": 'sichuan-mouth-watering-chicken',
    "香菇滑鸡": 'steamed-chicken-with-shiitake-mushrooms',
    "土豆炖鸡": 'chicken-and-potato-stew',
    "咖喱鸡": 'chicken-curry',
    "左宗棠鸡": 'general-tso-chicken',
    "啤酒鸭": 'beer-braised-duck',
    "酸萝卜老鸭汤": 'sour-radish-duck-soup',
    "盐水鸭": 'nanjing-salted-duck',
    "鸭血粉丝汤": 'duck-blood-vermicelli-soup',
    "清蒸鲈鱼": 'steamed-sea-bass-with-scallions',
    "红烧鱼": 'braised-fish-in-soy-sauce',
    "糖醋鱼": 'sweet-and-sour-fish',
    "酸菜鱼": 'sichuan-pickled-cabbage-fish',
    "水煮鱼": 'sichuan-boiled-fish-in-chili-oil',
    "烤鱼": 'grilled-fish-with-vegetables',
    "鱼头豆腐汤": 'fish-head-tofu-soup',
    "番茄鱼": 'tomato-fish-fillet-soup',
    "香煎带鱼": 'pan-fried-hairtail-fish',
    "红烧带鱼": 'braised-hairtail-fish',
    "清蒸鲳鱼": 'steamed-pomfret',
    "白灼虾": 'boiled-shrimp-with-dipping-sauce',
    "油焖大虾": 'braised-prawns-in-tomato-sauce',
    "蒜蓉粉丝虾": 'garlic-shrimp-with-vermicelli',
    "虾仁炒蛋": 'scrambled-eggs-with-shrimp',
    "椒盐虾": 'salt-and-pepper-shrimp',
    "香辣蟹": 'spicy-stir-fried-crab',
    "蒜蓉扇贝": 'garlic-steamed-scallops',
    "爆炒鱿鱼": 'stir-fried-squid-with-peppers',
    "蛤蜊汤": 'clam-soup',
    "麻婆豆腐": 'mapo-tofu',
    "家常豆腐": 'home-style-braised-tofu',
    "红烧豆腐": 'braised-tofu-in-brown-sauce',
    "酿豆腐": 'stuffed-tofu',
    "香干炒肉": 'stir-fried-pork-with-dried-tofu',
    "腐竹烧肉": 'braised-pork-with-dried-bean-curd-sticks',
    "清炒西兰花": 'stir-fried-broccoli-with-garlic',
    "蒜蓉西兰花": 'garlic-broccoli',
    "手撕包菜": 'hand-torn-cabbage-stir-fry',
    "醋溜白菜": 'sweet-and-sour-cabbage',
    "干煸四季豆": 'dry-fried-green-beans',
    "地三鲜": 'three-treasure-vegetables',
    "红烧茄子": 'braised-eggplant',
    "鱼香茄子": 'eggplant-in-garlic-sauce',
    "蒜泥茄子": 'steamed-eggplant-with-garlic',
    "清炒荷兰豆": 'stir-fried-snow-peas',
    "上汤娃娃菜": 'braised-baby-napa-cabbage-in-broth',
    "清炒油麦菜": 'stir-fried-leaf-lettuce',
    "蒜蓉菠菜": 'garlic-spinach',
    "清炒空心菜": 'stir-fried-water-spinach',
    "炒土豆丝": 'stir-fried-shredded-potatoes',
    "醋溜土豆丝": 'sweet-and-sour-potato-shreds',
    "干锅花菜": 'dry-pot-cauliflower-with-pork',
    "清炒藕片": 'stir-fried-lotus-root-slices',
    "蚝油生菜": 'lettuce-in-oyster-sauce',
    "清炒丝瓜": 'stir-fried-loofah',
    "西红柿炒菜花": 'stir-fried-cauliflower-with-tomatoes',
    "炒豆芽": 'stir-fried-bean-sprouts',
    "香菇青菜": 'shiitake-mushrooms-with-bok-choy',
    "清炒莴笋": 'stir-fried-celtuce',
    "清炒芦笋": 'stir-fried-asparagus',
    "炒南瓜": 'stir-fried-pumpkin',
    "西葫芦炒蛋": 'scrambled-eggs-with-zucchini',
    "凉拌黄瓜": 'smashed-cucumber-salad',
    "凉拌木耳": 'wood-ear-mushroom-salad',
    "凉拌海带丝": 'shredded-kelp-salad',
    "皮蛋豆腐": 'century-egg-with-tofu',
    "凉拌三丝": 'three-shredded-vegetable-salad',
    "凉拌粉丝": 'vermicelli-salad',
    "凉拌腐竹": 'dried-bean-curd-stick-salad',
    "醋泡花生": 'pickled-peanuts-in-vinegar',
    "凉拌莴笋丝": 'shredded-celtuce-salad',
    "蒜泥黄瓜": 'garlic-cucumber-salad',
    "凉拌豆干": 'dried-tofu-salad',
    "泡椒凤爪": 'chicken-feet-with-pickled-peppers',
    "蛋炒饭": 'egg-fried-rice',
    "扬州炒饭": 'yangzhou-fried-rice',
    "番茄鸡蛋面": 'tomato-and-egg-noodle-soup',
    "炸酱面": 'zhajiangmian-noodles-with-soybean-paste',
    "葱油拌面": 'scallion-oil-noodles',
    "阳春面": 'plain-noodle-soup',
    "炒面": 'stir-fried-noodles',
    "牛肉面": 'beef-noodle-soup',
    "饺子": 'chinese-dumplings',
    "包子": 'steamed-pork-buns',
    "馄饨": 'wonton-soup',
    "手抓饼": 'flaky-scallion-pancake',
    "葱油饼": 'scallion-pancake',
    "馒头": 'steamed-buns',
    "花卷": 'steamed-scallion-rolls',
    "煲仔饭": 'claypot-rice-with-chinese-sausage',
    "咖喱饭": 'curry-rice',
    "卤肉饭": 'taiwanese-braised-pork-rice',
    "炒河粉": 'beef-chow-fun',
    "炒米粉": 'stir-fried-rice-vermicelli',
    "酸辣粉": 'hot-and-sour-sweet-potato-noodles',
    "螺蛳粉": 'luosifen-rice-noodles',
    "凉皮": 'cold-skin-noodles',
    "小米粥": 'millet-porridge',
    "皮蛋瘦肉粥": 'century-egg-and-pork-congee',
    "白粥": 'plain-rice-congee',
    "豆浆油条": 'soy-milk-with-fried-dough-sticks',
    "三明治": 'sandwich',
    "牛奶麦片": 'milk-with-oatmeal',
    "蒸红薯": 'steamed-sweet-potatoes',
    "煮玉米": 'boiled-corn-on-the-cob',
    "茶叶蛋": 'tea-eggs',
    "煎荷包蛋": 'fried-eggs-sunny-side-up',
    "紫菜蛋花汤": 'seaweed-egg-drop-soup',
    "西红柿鸡蛋汤": 'tomato-egg-drop-soup',
    "冬瓜排骨汤": 'winter-melon-pork-rib-soup',
    "玉米排骨汤": 'corn-pork-rib-soup',
    "莲藕排骨汤": 'lotus-root-pork-rib-soup',
    "山药排骨汤": 'chinese-yam-pork-rib-soup',
    "老母鸡汤": 'chicken-soup',
    "银耳莲子汤": 'white-fungus-and-lotus-seed-soup',
    "绿豆汤": 'mung-bean-soup',
    "酸辣汤": 'hot-and-sour-soup',
    "罗宋汤": 'borscht-soup',
    "菌菇汤": 'mushroom-soup',
    "南瓜汤": 'pumpkin-soup',
    "玉米浓汤": 'corn-chowder-soup',
    "味噌汤": 'miso-soup',
    "番茄汤": 'tomato-soup',
    "紫菜汤": 'seaweed-soup',
    "春卷": 'spring-rolls',
    "锅贴": 'potstickers',
    "煎饺": 'pan-fried-dumplings',
    "炸鸡翅": 'fried-chicken-wings',
    "南瓜饼": 'pumpkin-pancakes',
    "红薯饼": 'sweet-potato-pancakes',
    "糯米糍": 'glutinous-rice-balls-with-red-bean',
    "汤圆": 'tangyuan-glutinous-rice-balls',
    "粽子": 'zongzi-sticky-rice-dumpling',
    "麻花": 'fried-dough-twists',
    "蛋挞": 'egg-tarts',
    "爆米花": 'popcorn',
    "糖葫芦": 'candied-hawthorn-skewers',
    "绿豆糕": 'mung-bean-cakes',
    "凤梨酥": 'pineapple-cakes',
    "蛋黄酥": 'salted-egg-yolk-pastries',
    "芋圆": 'taro-balls-dessert',
    "龟苓膏": 'turtle-jelly-dessert',
    "冰淇淋": 'ice-cream-scoops',
    "布丁": 'caramel-pudding',
}

DISH_CATEGORIES: dict[str, str] = {
    "西红柿炒鸡蛋": '家常热菜',
    "韭菜炒鸡蛋": '家常热菜',
    "洋葱炒鸡蛋": '家常热菜',
    "苦瓜炒鸡蛋": '家常热菜',
    "黄瓜炒鸡蛋": '家常热菜',
    "木耳炒鸡蛋": '家常热菜',
    "青椒炒鸡蛋": '家常热菜',
    "蒸蛋羹": '家常热菜',
    "虎皮鸡蛋": '家常热菜',
    "木须肉": '家常热菜',
    "红烧肉": '家常热菜',
    "回锅肉": '家常热菜',
    "青椒炒肉丝": '家常热菜',
    "鱼香肉丝": '家常热菜',
    "糖醋里脊": '家常热菜',
    "京酱肉丝": '家常热菜',
    "梅菜扣肉": '家常热菜',
    "蒜泥白肉": '家常热菜',
    "粉蒸肉": '家常热菜',
    "红烧排骨": '家常热菜',
    "糖醋排骨": '家常热菜',
    "肉末茄子": '家常热菜',
    "肉末豆腐": '家常热菜',
    "蚂蚁上树": '家常热菜',
    "猪肉炖粉条": '家常热菜',
    "白菜炖粉条": '家常热菜',
    "狮子头": '家常热菜',
    "芹菜炒肉": '家常热菜',
    "蒜薹炒肉": '家常热菜',
    "土豆炖肉": '家常热菜',
    "西红柿牛腩": '家常热菜',
    "土豆炖牛肉": '家常热菜',
    "黑椒牛柳": '家常热菜',
    "蚝油牛肉": '家常热菜',
    "水煮牛肉": '家常热菜',
    "小炒黄牛肉": '家常热菜',
    "孜然牛肉": '家常热菜',
    "洋葱炒牛肉": '家常热菜',
    "葱爆羊肉": '家常热菜',
    "孜然羊肉": '家常热菜',
    "白萝卜炖羊肉": '家常热菜',
    "宫保鸡丁": '家常热菜',
    "辣子鸡": '家常热菜',
    "黄焖鸡": '家常热菜',
    "大盘鸡": '家常热菜',
    "三杯鸡": '家常热菜',
    "可乐鸡翅": '家常热菜',
    "白切鸡": '家常热菜',
    "口水鸡": '家常热菜',
    "香菇滑鸡": '家常热菜',
    "土豆炖鸡": '家常热菜',
    "咖喱鸡": '家常热菜',
    "左宗棠鸡": '家常热菜',
    "啤酒鸭": '家常热菜',
    "酸萝卜老鸭汤": '汤羹',
    "盐水鸭": '家常热菜',
    "鸭血粉丝汤": '汤羹',
    "清蒸鲈鱼": '家常热菜',
    "红烧鱼": '家常热菜',
    "糖醋鱼": '家常热菜',
    "酸菜鱼": '家常热菜',
    "水煮鱼": '家常热菜',
    "烤鱼": '家常热菜',
    "鱼头豆腐汤": '汤羹',
    "番茄鱼": '家常热菜',
    "香煎带鱼": '家常热菜',
    "红烧带鱼": '家常热菜',
    "清蒸鲳鱼": '家常热菜',
    "白灼虾": '家常热菜',
    "油焖大虾": '家常热菜',
    "蒜蓉粉丝虾": '家常热菜',
    "虾仁炒蛋": '家常热菜',
    "椒盐虾": '家常热菜',
    "香辣蟹": '家常热菜',
    "蒜蓉扇贝": '家常热菜',
    "爆炒鱿鱼": '家常热菜',
    "蛤蜊汤": '汤羹',
    "麻婆豆腐": '家常热菜',
    "家常豆腐": '家常热菜',
    "红烧豆腐": '家常热菜',
    "酿豆腐": '家常热菜',
    "香干炒肉": '家常热菜',
    "腐竹烧肉": '家常热菜',
    "清炒西兰花": '家常热菜',
    "蒜蓉西兰花": '家常热菜',
    "手撕包菜": '家常热菜',
    "醋溜白菜": '家常热菜',
    "干煸四季豆": '家常热菜',
    "地三鲜": '家常热菜',
    "红烧茄子": '家常热菜',
    "鱼香茄子": '家常热菜',
    "蒜泥茄子": '家常热菜',
    "清炒荷兰豆": '家常热菜',
    "上汤娃娃菜": '家常热菜',
    "清炒油麦菜": '家常热菜',
    "蒜蓉菠菜": '家常热菜',
    "清炒空心菜": '家常热菜',
    "炒土豆丝": '家常热菜',
    "醋溜土豆丝": '家常热菜',
    "干锅花菜": '家常热菜',
    "清炒藕片": '家常热菜',
    "蚝油生菜": '家常热菜',
    "清炒丝瓜": '家常热菜',
    "西红柿炒菜花": '家常热菜',
    "炒豆芽": '家常热菜',
    "香菇青菜": '家常热菜',
    "清炒莴笋": '家常热菜',
    "清炒芦笋": '家常热菜',
    "炒南瓜": '家常热菜',
    "西葫芦炒蛋": '家常热菜',
    "凉拌黄瓜": '凉菜',
    "凉拌木耳": '凉菜',
    "凉拌海带丝": '凉菜',
    "皮蛋豆腐": '凉菜',
    "凉拌三丝": '凉菜',
    "凉拌粉丝": '凉菜',
    "凉拌腐竹": '凉菜',
    "醋泡花生": '凉菜',
    "凉拌莴笋丝": '凉菜',
    "蒜泥黄瓜": '凉菜',
    "凉拌豆干": '凉菜',
    "泡椒凤爪": '凉菜',
    "蛋炒饭": '主食',
    "扬州炒饭": '主食',
    "番茄鸡蛋面": '主食',
    "炸酱面": '主食',
    "葱油拌面": '主食',
    "阳春面": '主食',
    "炒面": '主食',
    "牛肉面": '主食',
    "饺子": '主食',
    "包子": '主食',
    "馄饨": '主食',
    "手抓饼": '主食',
    "葱油饼": '主食',
    "馒头": '主食',
    "花卷": '主食',
    "煲仔饭": '主食',
    "咖喱饭": '主食',
    "卤肉饭": '主食',
    "炒河粉": '主食',
    "炒米粉": '主食',
    "酸辣粉": '主食',
    "螺蛳粉": '主食',
    "凉皮": '主食',
    "小米粥": '早餐',
    "皮蛋瘦肉粥": '早餐',
    "白粥": '早餐',
    "豆浆油条": '早餐',
    "三明治": '早餐',
    "牛奶麦片": '早餐',
    "蒸红薯": '早餐',
    "煮玉米": '早餐',
    "茶叶蛋": '早餐',
    "煎荷包蛋": '早餐',
    "紫菜蛋花汤": '汤羹',
    "西红柿鸡蛋汤": '汤羹',
    "冬瓜排骨汤": '汤羹',
    "玉米排骨汤": '汤羹',
    "莲藕排骨汤": '汤羹',
    "山药排骨汤": '汤羹',
    "老母鸡汤": '汤羹',
    "银耳莲子汤": '汤羹',
    "绿豆汤": '汤羹',
    "酸辣汤": '汤羹',
    "罗宋汤": '汤羹',
    "菌菇汤": '汤羹',
    "南瓜汤": '汤羹',
    "玉米浓汤": '汤羹',
    "味噌汤": '汤羹',
    "番茄汤": '汤羹',
    "紫菜汤": '汤羹',
    "春卷": '小吃点心',
    "锅贴": '小吃点心',
    "煎饺": '小吃点心',
    "炸鸡翅": '小吃点心',
    "南瓜饼": '小吃点心',
    "红薯饼": '小吃点心',
    "糯米糍": '小吃点心',
    "汤圆": '小吃点心',
    "粽子": '小吃点心',
    "麻花": '小吃点心',
    "蛋挞": '小吃点心',
    "爆米花": '小吃点心',
    "糖葫芦": '小吃点心',
    "绿豆糕": '小吃点心',
    "凤梨酥": '小吃点心',
    "蛋黄酥": '小吃点心',
    "芋圆": '小吃点心',
    "龟苓膏": '小吃点心',
    "冰淇淋": '小吃点心',
    "布丁": '小吃点心',
}

# 菜名 -> (必需食材, 可选食材)。元素都是**图片 key**，不是中文名。
DISH_INGREDIENTS: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "西红柿炒鸡蛋": (('tomato', 'egg'), ('spring-onion',)),
    "韭菜炒鸡蛋": (('chives', 'egg'), ()),
    "洋葱炒鸡蛋": (('onion', 'egg'), ()),
    "苦瓜炒鸡蛋": (('bitter-melon', 'egg'), ()),
    "黄瓜炒鸡蛋": (('cucumber', 'egg'), ()),
    "木耳炒鸡蛋": (('wood-ear-fungus', 'egg'), ()),
    "青椒炒鸡蛋": (('green-pepper', 'egg'), ()),
    "蒸蛋羹": (('egg',), ('spring-onion', 'seasoning')),
    "虎皮鸡蛋": (('egg',), ('soy-sauce', 'rock-sugar')),
    "木须肉": (('egg', 'pork', 'wood-ear-fungus'), ('cucumber',)),
    "红烧肉": (('pork-belly',), ('rock-sugar', 'ginger', 'star-anise', 'cooking-wine')),
    "回锅肉": (('pork-belly', 'green-pepper'), ('doubanjiang', 'garlic-sprout')),
    "青椒炒肉丝": (('pork', 'green-pepper'), ('garlic',)),
    "鱼香肉丝": (('pork', 'wood-ear-fungus', 'carrot'), ('green-pepper', 'doubanjiang')),
    "糖醋里脊": (('pork-tenderloin',), ('seasoning', 'white-sugar', 'vinegar')),
    "京酱肉丝": (('pork-tenderloin', 'scallion'), ('sweet-bean-sauce',)),
    "梅菜扣肉": (('pork-belly',), ('potherb-mustard', 'soy-sauce')),
    "蒜泥白肉": (('pork-belly',), ('garlic', 'chili-pepper')),
    "粉蒸肉": (('pork-belly',), ('rice', 'sweet-potato')),
    "红烧排骨": (('pork-ribs',), ('rock-sugar', 'soy-sauce', 'ginger')),
    "糖醋排骨": (('pork-ribs',), ('white-sugar', 'vinegar')),
    "肉末茄子": (('ground-pork', 'eggplant'), ('garlic', 'spring-onion')),
    "肉末豆腐": (('ground-pork', 'tofu'), ('spring-onion', 'doubanjiang')),
    "蚂蚁上树": (('ground-pork', 'glass-noodles'), ('doubanjiang', 'spring-onion')),
    "猪肉炖粉条": (('pork-belly', 'starch-noodles'), ('napa-cabbage',)),
    "白菜炖粉条": (('napa-cabbage', 'starch-noodles'), ('pork',)),
    "狮子头": (('ground-pork',), ('water-chestnut', 'egg')),
    "芹菜炒肉": (('celery', 'pork'), ()),
    "蒜薹炒肉": (('garlic-sprout', 'pork'), ()),
    "土豆炖肉": (('potato', 'pork-belly'), ('carrot',)),
    "西红柿牛腩": (('tomato', 'beef-brisket'), ('onion',)),
    "土豆炖牛肉": (('potato', 'beef'), ('carrot',)),
    "黑椒牛柳": (('beef-steak', 'onion'), ('black-pepper',)),
    "蚝油牛肉": (('beef', 'oyster-sauce'), ('green-pepper',)),
    "水煮牛肉": (('beef', 'soybean-sprouts'), ('dried-chili', 'sichuan-peppercorn')),
    "小炒黄牛肉": (('beef', 'chili-pepper'), ('garlic',)),
    "孜然牛肉": (('beef', 'cumin'), ('onion',)),
    "洋葱炒牛肉": (('onion', 'beef'), ()),
    "葱爆羊肉": (('lamb', 'scallion'), ()),
    "孜然羊肉": (('lamb', 'cumin'), ('onion',)),
    "白萝卜炖羊肉": (('daikon-radish', 'lamb'), ('ginger',)),
    "宫保鸡丁": (('chicken-breast', 'peanut'), ('dried-chili', 'scallion', 'sichuan-peppercorn')),
    "辣子鸡": (('chicken-leg', 'dried-chili'), ('sichuan-peppercorn', 'garlic')),
    "黄焖鸡": (('chicken-leg', 'shiitake-mushroom'), ('green-pepper', 'potato')),
    "大盘鸡": (('chicken-leg', 'potato'), ('green-pepper', 'noodles')),
    "三杯鸡": (('chicken-leg',), ('ginger', 'basil', 'seasoning')),
    "可乐鸡翅": (('chicken-wing',), ('soft-drink', 'ginger')),
    "白切鸡": (('chicken',), ('ginger', 'spring-onion')),
    "口水鸡": (('chicken-leg',), ('chili-pepper', 'peanut', 'spring-onion')),
    "香菇滑鸡": (('chicken-leg', 'shiitake-mushroom'), ('ginger', 'oyster-sauce')),
    "土豆炖鸡": (('potato', 'chicken'), ('carrot',)),
    "咖喱鸡": (('chicken-leg', 'curry-powder'), ('potato', 'carrot', 'onion')),
    "左宗棠鸡": (('chicken-leg',), ('dried-chili', 'seasoning')),
    "啤酒鸭": (('duck', 'beer'), ('ginger', 'star-anise')),
    "酸萝卜老鸭汤": (('duck', 'daikon-radish'), ('ginger', 'pickled-cabbage')),
    "盐水鸭": (('duck',), ('sichuan-peppercorn', 'ginger')),
    "鸭血粉丝汤": (('duck-blood', 'glass-noodles'), ('duck-gizzard', 'spring-onion')),
    "清蒸鲈鱼": (('sea-bass',), ('scallion', 'ginger')),
    "红烧鱼": (('crucian-carp',), ('ginger', 'soy-sauce', 'cooking-wine')),
    "糖醋鱼": (('grass-carp',), ('seasoning', 'white-sugar')),
    "酸菜鱼": (('snakehead-fish', 'pickled-cabbage'), ('kimchi', 'dried-chili')),
    "水煮鱼": (('grass-carp', 'soybean-sprouts'), ('dried-chili', 'sichuan-peppercorn')),
    "烤鱼": (('grass-carp',), ('potato', 'onion', 'dried-chili')),
    "鱼头豆腐汤": (('bighead-carp', 'tofu'), ('ginger', 'spring-onion')),
    "番茄鱼": (('tomato', 'snakehead-fish'), ('ginger',)),
    "香煎带鱼": (('hairtail-fish',), ('wheat-flour', 'ginger')),
    "红烧带鱼": (('hairtail-fish',), ('ginger', 'soy-sauce', 'cooking-wine')),
    "清蒸鲳鱼": (('pomfret',), ('scallion', 'ginger')),
    "白灼虾": (('shrimp',), ('ginger', 'light-soy-sauce')),
    "油焖大虾": (('shrimp',), ('seasoning', 'white-sugar')),
    "蒜蓉粉丝虾": (('shrimp', 'glass-noodles', 'garlic'), ('spring-onion',)),
    "虾仁炒蛋": (('peeled-shrimp', 'egg'), ('spring-onion',)),
    "椒盐虾": (('shrimp',), ('sichuan-peppercorn', 'salt')),
    "香辣蟹": (('crab', 'dried-chili'), ('sichuan-peppercorn', 'garlic')),
    "蒜蓉扇贝": (('scallop', 'garlic', 'glass-noodles'), ('spring-onion',)),
    "爆炒鱿鱼": (('squid', 'green-pepper'), ('onion', 'garlic')),
    "蛤蜊汤": (('littleneck-clam',), ('ginger', 'spring-onion')),
    "麻婆豆腐": (('tofu', 'ground-pork'), ('doubanjiang', 'sichuan-peppercorn', 'spring-onion')),
    "家常豆腐": (('tofu', 'green-pepper'), ('carrot', 'wood-ear-fungus')),
    "红烧豆腐": (('tofu',), ('spring-onion', 'oyster-sauce')),
    "酿豆腐": (('tofu', 'ground-pork'), ('spring-onion',)),
    "香干炒肉": (('dried-tofu', 'pork'), ('green-pepper',)),
    "腐竹烧肉": (('tofu-skin', 'pork-belly'), ('soy-sauce',)),
    "清炒西兰花": (('broccoli',), ('garlic',)),
    "蒜蓉西兰花": (('broccoli', 'garlic'), ()),
    "手撕包菜": (('napa-cabbage', 'dried-chili'), ('garlic',)),
    "醋溜白菜": (('napa-cabbage', 'vinegar'), ('dried-chili',)),
    "干煸四季豆": (('green-beans', 'ground-pork'), ('dried-chili', 'garlic')),
    "地三鲜": (('potato', 'eggplant', 'green-pepper'), ('garlic',)),
    "红烧茄子": (('eggplant',), ('garlic', 'soy-sauce', 'white-sugar')),
    "鱼香茄子": (('eggplant', 'ground-pork'), ('doubanjiang', 'garlic')),
    "蒜泥茄子": (('eggplant', 'garlic'), ('seasoning',)),
    "清炒荷兰豆": (('snow-peas',), ('garlic',)),
    "上汤娃娃菜": (('baby-napa-cabbage',), ('century-egg',)),
    "清炒油麦菜": (('leaf-lettuce',), ('garlic',)),
    "蒜蓉菠菜": (('spinach', 'garlic'), ()),
    "清炒空心菜": (('water-spinach',), ('garlic',)),
    "炒土豆丝": (('potato',), ('green-pepper', 'vinegar')),
    "醋溜土豆丝": (('potato', 'vinegar'), ('dried-chili',)),
    "干锅花菜": (('broccoli', 'pork-belly'), ('dried-chili', 'garlic')),
    "清炒藕片": (('lotus-root',), ('garlic', 'spring-onion')),
    "蚝油生菜": (('lettuce', 'oyster-sauce'), ('garlic',)),
    "清炒丝瓜": (('loofah',), ('garlic',)),
    "西红柿炒菜花": (('tomato', 'broccoli'), ()),
    "炒豆芽": (('mung-bean-sprouts',), ('chives', 'garlic')),
    "香菇青菜": (('shiitake-mushroom', 'shanghai-green'), ('oyster-sauce',)),
    "清炒莴笋": (('celtuce',), ('garlic',)),
    "清炒芦笋": (('asparagus',), ('garlic',)),
    "炒南瓜": (('pumpkin',), ('garlic',)),
    "西葫芦炒蛋": (('zucchini', 'egg'), ()),
    "凉拌黄瓜": (('cucumber', 'garlic'), ('vinegar', 'seasoning')),
    "凉拌木耳": (('wood-ear-fungus',), ('green-pepper', 'vinegar', 'garlic')),
    "凉拌海带丝": (('kelp', 'garlic'), ('vinegar', 'chili-pepper')),
    "皮蛋豆腐": (('century-egg', 'tofu'), ('spring-onion', 'seasoning')),
    "凉拌三丝": (('carrot', 'cucumber', 'glass-noodles'), ('vinegar', 'seasoning')),
    "凉拌粉丝": (('glass-noodles', 'cucumber'), ('vinegar', 'garlic')),
    "凉拌腐竹": (('tofu-skin', 'cucumber'), ('vinegar', 'garlic')),
    "醋泡花生": (('peanut', 'vinegar'), ('celery',)),
    "凉拌莴笋丝": (('celtuce', 'carrot'), ('vinegar', 'seasoning')),
    "蒜泥黄瓜": (('cucumber', 'garlic'), ('vinegar',)),
    "凉拌豆干": (('dried-tofu', 'celery'), ('vinegar', 'chili-pepper')),
    "泡椒凤爪": (('chicken-feet', 'kimchi'), ('sichuan-peppercorn',)),
    "蛋炒饭": (('egg', 'rice'), ('spring-onion', 'ham')),
    "扬州炒饭": (('egg', 'rice', 'peeled-shrimp'), ('ham', 'green-beans', 'carrot')),
    "番茄鸡蛋面": (('tomato', 'egg', 'noodles'), ('spring-onion',)),
    "炸酱面": (('noodles', 'ground-pork', 'soybean-paste'), ('cucumber', 'soybean-sprouts')),
    "葱油拌面": (('noodles', 'spring-onion'), ('soy-sauce', 'seasoning')),
    "阳春面": (('noodles', 'spring-onion'), ('lard', 'soy-sauce')),
    "炒面": (('noodles', 'napa-cabbage'), ('carrot', 'pork')),
    "牛肉面": (('noodles', 'beef'), ('daikon-radish', 'cilantro')),
    "饺子": (('dumpling-wrapper', 'ground-pork'), ('napa-cabbage', 'chives')),
    "包子": (('wheat-flour', 'ground-pork'), ('napa-cabbage', 'yeast')),
    "馄饨": (('wonton-wrapper', 'ground-pork'), ('nori',)),
    "手抓饼": (('wheat-flour', 'egg'), ('lettuce', 'ham')),
    "葱油饼": (('wheat-flour', 'spring-onion'), ('salt',)),
    "馒头": (('wheat-flour', 'yeast'), ()),
    "花卷": (('wheat-flour', 'yeast', 'spring-onion'), ()),
    "煲仔饭": (('rice', 'sausage', 'egg'), ('shanghai-green',)),
    "咖喱饭": (('rice', 'curry-powder', 'potato'), ('carrot', 'chicken-leg')),
    "卤肉饭": (('rice', 'pork-belly'), ('egg', 'soy-sauce')),
    "炒河粉": (('rice-noodle-sheet', 'beef', 'soybean-sprouts'), ('onion', 'spring-onion')),
    "炒米粉": (('rice-noodles', 'carrot', 'napa-cabbage'), ('pork', 'shiitake-mushroom')),
    "酸辣粉": (('sweet-potato-noodles', 'vinegar', 'chili-pepper'), ('peanut', 'cilantro')),
    "螺蛳粉": (('rice-noodles', 'pickled-cabbage'), ('peanut', 'tofu-skin', 'pickled-long-beans')),
    "凉皮": (('wheat-flour', 'cucumber', 'vinegar'), ('garlic', 'chili-pepper')),
    "小米粥": (('millet',), ('dried-red-date', 'pumpkin')),
    "皮蛋瘦肉粥": (('rice', 'century-egg', 'pork'), ('spring-onion',)),
    "白粥": (('rice',), ()),
    "豆浆油条": (('soybean', 'wheat-flour'), ()),
    "三明治": (('bread', 'egg', 'lettuce'), ('ham', 'tomato')),
    "牛奶麦片": (('milk', 'oats'), ()),
    "蒸红薯": (('sweet-potato',), ()),
    "煮玉米": (('corn',), ()),
    "茶叶蛋": (('egg', 'black-tea'), ('soy-sauce', 'star-anise')),
    "煎荷包蛋": (('egg',), ('salt', 'black-pepper')),
    "紫菜蛋花汤": (('nori', 'egg'), ('spring-onion',)),
    "西红柿鸡蛋汤": (('tomato', 'egg'), ('spring-onion',)),
    "冬瓜排骨汤": (('winter-melon', 'pork-ribs'), ('ginger', 'spring-onion')),
    "玉米排骨汤": (('corn', 'pork-ribs'), ('carrot', 'ginger')),
    "莲藕排骨汤": (('lotus-root', 'pork-ribs'), ('ginger',)),
    "山药排骨汤": (('chinese-yam', 'pork-ribs'), ('ginger',)),
    "老母鸡汤": (('chicken', 'ginger'), ('dried-red-date',)),
    "银耳莲子汤": (('white-fungus', 'lotus-seed'), ('dried-red-date', 'rock-sugar')),
    "绿豆汤": (('mung-bean', 'white-sugar'), ()),
    "酸辣汤": (('tofu', 'wood-ear-fungus', 'egg'), ('vinegar', 'white-pepper')),
    "罗宋汤": (('tomato', 'beef', 'potato'), ('carrot', 'onion')),
    "菌菇汤": (('shiitake-mushroom', 'enoki-mushroom', 'oyster-mushroom'), ()),
    "南瓜汤": (('pumpkin', 'milk'), ('light-cream',)),
    "玉米浓汤": (('corn', 'milk'), ('butter', 'wheat-flour')),
    "味噌汤": (('miso', 'tofu'), ('nori', 'spring-onion')),
    "番茄汤": (('tomato', 'egg'), ('onion',)),
    "紫菜汤": (('nori', 'egg'), ()),
    "春卷": (('spring-roll-wrapper', 'napa-cabbage', 'carrot'), ('pork',)),
    "锅贴": (('dumpling-wrapper', 'ground-pork'), ('napa-cabbage',)),
    "煎饺": (('dumpling-wrapper', 'ground-pork', 'napa-cabbage'), ()),
    "炸鸡翅": (('chicken-wing', 'wheat-flour'), ('black-pepper', 'egg')),
    "南瓜饼": (('pumpkin', 'glutinous-rice-flour'), ('white-sugar',)),
    "红薯饼": (('sweet-potato', 'wheat-flour'), ('white-sugar',)),
    "糯米糍": (('glutinous-rice-flour', 'red-bean'), ('coconut',)),
    "汤圆": (('glutinous-rice-flour',), ('white-sugar',)),
    "粽子": (('glutinous-rice', 'pork-belly'), ()),
    "麻花": (('wheat-flour', 'white-sugar'), ('egg',)),
    "蛋挞": (('wheat-flour', 'egg', 'milk'), ('butter',)),
    "爆米花": (('corn', 'butter'), ()),
    "糖葫芦": (('hawthorn', 'rock-sugar'), ()),
    "绿豆糕": (('mung-bean', 'white-sugar'), ()),
    "凤梨酥": (('pineapple', 'wheat-flour', 'butter'), ('egg',)),
    "蛋黄酥": (('wheat-flour', 'salted-duck-egg', 'red-bean'), ('butter',)),
    "芋圆": (('taro', 'tapioca-starch'), ('red-bean',)),
    "龟苓膏": (('honey',), ()),
    "冰淇淋": (('milk', 'light-cream', 'white-sugar'), ()),
    "布丁": (('milk', 'egg', 'white-sugar'), ()),
}

# 食材 key -> **必需**它的菜名。推荐用这张。
BY_REQUIRED: dict[str, tuple[str, ...]] = {
    "asparagus": ('清炒芦笋',),
    "baby-napa-cabbage": ('上汤娃娃菜',),
    "beef": ('土豆炖牛肉', '蚝油牛肉', '水煮牛肉', '小炒黄牛肉', '孜然牛肉', '洋葱炒牛肉', '牛肉面', '炒河粉', '罗宋汤'),
    "beef-brisket": ('西红柿牛腩',),
    "beef-steak": ('黑椒牛柳',),
    "beer": ('啤酒鸭',),
    "bighead-carp": ('鱼头豆腐汤',),
    "bitter-melon": ('苦瓜炒鸡蛋',),
    "black-tea": ('茶叶蛋',),
    "bread": ('三明治',),
    "broccoli": ('清炒西兰花', '蒜蓉西兰花', '干锅花菜', '西红柿炒菜花'),
    "butter": ('爆米花', '凤梨酥'),
    "carrot": ('鱼香肉丝', '凉拌三丝', '凉拌莴笋丝', '炒米粉', '春卷'),
    "celery": ('芹菜炒肉', '凉拌豆干'),
    "celtuce": ('清炒莴笋', '凉拌莴笋丝'),
    "century-egg": ('皮蛋豆腐', '皮蛋瘦肉粥'),
    "chicken": ('白切鸡', '土豆炖鸡', '老母鸡汤'),
    "chicken-breast": ('宫保鸡丁',),
    "chicken-feet": ('泡椒凤爪',),
    "chicken-leg": ('辣子鸡', '黄焖鸡', '大盘鸡', '三杯鸡', '口水鸡', '香菇滑鸡', '咖喱鸡', '左宗棠鸡'),
    "chicken-wing": ('可乐鸡翅', '炸鸡翅'),
    "chili-pepper": ('小炒黄牛肉', '酸辣粉'),
    "chinese-yam": ('山药排骨汤',),
    "chives": ('韭菜炒鸡蛋',),
    "corn": ('煮玉米', '玉米排骨汤', '玉米浓汤', '爆米花'),
    "crab": ('香辣蟹',),
    "crucian-carp": ('红烧鱼',),
    "cucumber": ('黄瓜炒鸡蛋', '凉拌黄瓜', '凉拌三丝', '凉拌粉丝', '凉拌腐竹', '蒜泥黄瓜', '凉皮'),
    "cumin": ('孜然牛肉', '孜然羊肉'),
    "curry-powder": ('咖喱鸡', '咖喱饭'),
    "daikon-radish": ('白萝卜炖羊肉', '酸萝卜老鸭汤'),
    "dried-chili": ('辣子鸡', '香辣蟹', '手撕包菜'),
    "dried-tofu": ('香干炒肉', '凉拌豆干'),
    "duck": ('啤酒鸭', '酸萝卜老鸭汤', '盐水鸭'),
    "duck-blood": ('鸭血粉丝汤',),
    "dumpling-wrapper": ('饺子', '锅贴', '煎饺'),
    "egg": ('西红柿炒鸡蛋', '韭菜炒鸡蛋', '洋葱炒鸡蛋', '苦瓜炒鸡蛋', '黄瓜炒鸡蛋', '木耳炒鸡蛋', '青椒炒鸡蛋', '蒸蛋羹', '虎皮鸡蛋', '木须肉', '虾仁炒蛋', '西葫芦炒蛋', '蛋炒饭', '扬州炒饭', '番茄鸡蛋面', '手抓饼', '煲仔饭', '三明治', '茶叶蛋', '煎荷包蛋', '紫菜蛋花汤', '西红柿鸡蛋汤', '酸辣汤', '番茄汤', '紫菜汤', '蛋挞', '布丁'),
    "eggplant": ('肉末茄子', '地三鲜', '红烧茄子', '鱼香茄子', '蒜泥茄子'),
    "enoki-mushroom": ('菌菇汤',),
    "garlic": ('蒜蓉粉丝虾', '蒜蓉扇贝', '蒜蓉西兰花', '蒜泥茄子', '蒜蓉菠菜', '凉拌黄瓜', '凉拌海带丝', '蒜泥黄瓜'),
    "garlic-sprout": ('蒜薹炒肉',),
    "ginger": ('老母鸡汤',),
    "glass-noodles": ('蚂蚁上树', '鸭血粉丝汤', '蒜蓉粉丝虾', '蒜蓉扇贝', '凉拌三丝', '凉拌粉丝'),
    "glutinous-rice": ('粽子',),
    "glutinous-rice-flour": ('南瓜饼', '糯米糍', '汤圆'),
    "grass-carp": ('糖醋鱼', '水煮鱼', '烤鱼'),
    "green-beans": ('干煸四季豆',),
    "green-pepper": ('青椒炒鸡蛋', '回锅肉', '青椒炒肉丝', '爆炒鱿鱼', '家常豆腐', '地三鲜'),
    "ground-pork": ('肉末茄子', '肉末豆腐', '蚂蚁上树', '狮子头', '麻婆豆腐', '酿豆腐', '干煸四季豆', '鱼香茄子', '炸酱面', '饺子', '包子', '馄饨', '锅贴', '煎饺'),
    "hairtail-fish": ('香煎带鱼', '红烧带鱼'),
    "hawthorn": ('糖葫芦',),
    "honey": ('龟苓膏',),
    "kelp": ('凉拌海带丝',),
    "kimchi": ('泡椒凤爪',),
    "lamb": ('葱爆羊肉', '孜然羊肉', '白萝卜炖羊肉'),
    "leaf-lettuce": ('清炒油麦菜',),
    "lettuce": ('蚝油生菜', '三明治'),
    "light-cream": ('冰淇淋',),
    "littleneck-clam": ('蛤蜊汤',),
    "loofah": ('清炒丝瓜',),
    "lotus-root": ('清炒藕片', '莲藕排骨汤'),
    "lotus-seed": ('银耳莲子汤',),
    "milk": ('牛奶麦片', '南瓜汤', '玉米浓汤', '蛋挞', '冰淇淋', '布丁'),
    "millet": ('小米粥',),
    "miso": ('味噌汤',),
    "mung-bean": ('绿豆汤', '绿豆糕'),
    "mung-bean-sprouts": ('炒豆芽',),
    "napa-cabbage": ('白菜炖粉条', '手撕包菜', '醋溜白菜', '炒面', '炒米粉', '春卷', '煎饺'),
    "noodles": ('番茄鸡蛋面', '炸酱面', '葱油拌面', '阳春面', '炒面', '牛肉面'),
    "nori": ('紫菜蛋花汤', '紫菜汤'),
    "oats": ('牛奶麦片',),
    "onion": ('洋葱炒鸡蛋', '黑椒牛柳', '洋葱炒牛肉'),
    "oyster-mushroom": ('菌菇汤',),
    "oyster-sauce": ('蚝油牛肉', '蚝油生菜'),
    "peanut": ('宫保鸡丁', '醋泡花生'),
    "peeled-shrimp": ('虾仁炒蛋', '扬州炒饭'),
    "pickled-cabbage": ('酸菜鱼', '螺蛳粉'),
    "pineapple": ('凤梨酥',),
    "pomfret": ('清蒸鲳鱼',),
    "pork": ('木须肉', '青椒炒肉丝', '鱼香肉丝', '芹菜炒肉', '蒜薹炒肉', '香干炒肉', '皮蛋瘦肉粥'),
    "pork-belly": ('红烧肉', '回锅肉', '梅菜扣肉', '蒜泥白肉', '粉蒸肉', '猪肉炖粉条', '土豆炖肉', '腐竹烧肉', '干锅花菜', '卤肉饭', '粽子'),
    "pork-ribs": ('红烧排骨', '糖醋排骨', '冬瓜排骨汤', '玉米排骨汤', '莲藕排骨汤', '山药排骨汤'),
    "pork-tenderloin": ('糖醋里脊', '京酱肉丝'),
    "potato": ('土豆炖肉', '土豆炖牛肉', '大盘鸡', '土豆炖鸡', '地三鲜', '炒土豆丝', '醋溜土豆丝', '咖喱饭', '罗宋汤'),
    "pumpkin": ('炒南瓜', '南瓜汤', '南瓜饼'),
    "red-bean": ('糯米糍', '蛋黄酥'),
    "rice": ('蛋炒饭', '扬州炒饭', '煲仔饭', '咖喱饭', '卤肉饭', '皮蛋瘦肉粥', '白粥'),
    "rice-noodle-sheet": ('炒河粉',),
    "rice-noodles": ('炒米粉', '螺蛳粉'),
    "rock-sugar": ('糖葫芦',),
    "salted-duck-egg": ('蛋黄酥',),
    "sausage": ('煲仔饭',),
    "scallion": ('京酱肉丝', '葱爆羊肉'),
    "scallop": ('蒜蓉扇贝',),
    "sea-bass": ('清蒸鲈鱼',),
    "shanghai-green": ('香菇青菜',),
    "shiitake-mushroom": ('黄焖鸡', '香菇滑鸡', '香菇青菜', '菌菇汤'),
    "shrimp": ('白灼虾', '油焖大虾', '蒜蓉粉丝虾', '椒盐虾'),
    "snakehead-fish": ('酸菜鱼', '番茄鱼'),
    "snow-peas": ('清炒荷兰豆',),
    "soybean": ('豆浆油条',),
    "soybean-paste": ('炸酱面',),
    "soybean-sprouts": ('水煮牛肉', '水煮鱼', '炒河粉'),
    "spinach": ('蒜蓉菠菜',),
    "spring-onion": ('葱油拌面', '阳春面', '葱油饼', '花卷'),
    "spring-roll-wrapper": ('春卷',),
    "squid": ('爆炒鱿鱼',),
    "starch-noodles": ('猪肉炖粉条', '白菜炖粉条'),
    "sweet-potato": ('蒸红薯', '红薯饼'),
    "sweet-potato-noodles": ('酸辣粉',),
    "tapioca-starch": ('芋圆',),
    "taro": ('芋圆',),
    "tofu": ('肉末豆腐', '鱼头豆腐汤', '麻婆豆腐', '家常豆腐', '红烧豆腐', '酿豆腐', '皮蛋豆腐', '酸辣汤', '味噌汤'),
    "tofu-skin": ('腐竹烧肉', '凉拌腐竹'),
    "tomato": ('西红柿炒鸡蛋', '西红柿牛腩', '番茄鱼', '西红柿炒菜花', '番茄鸡蛋面', '西红柿鸡蛋汤', '罗宋汤', '番茄汤'),
    "vinegar": ('醋溜白菜', '醋溜土豆丝', '醋泡花生', '酸辣粉', '凉皮'),
    "water-spinach": ('清炒空心菜',),
    "wheat-flour": ('包子', '手抓饼', '葱油饼', '馒头', '花卷', '凉皮', '豆浆油条', '炸鸡翅', '红薯饼', '麻花', '蛋挞', '凤梨酥', '蛋黄酥'),
    "white-fungus": ('银耳莲子汤',),
    "white-sugar": ('绿豆汤', '麻花', '绿豆糕', '冰淇淋', '布丁'),
    "winter-melon": ('冬瓜排骨汤',),
    "wonton-wrapper": ('馄饨',),
    "wood-ear-fungus": ('木耳炒鸡蛋', '木须肉', '鱼香肉丝', '凉拌木耳', '酸辣汤'),
    "yeast": ('馒头', '花卷'),
    "zucchini": ('西葫芦炒蛋',),
}

# 食材 key -> 用到它的菜名（必需 + 可选）。搜索用这张。
BY_ANY: dict[str, tuple[str, ...]] = {
    "asparagus": ('清炒芦笋',),
    "baby-napa-cabbage": ('上汤娃娃菜',),
    "basil": ('三杯鸡',),
    "beef": ('土豆炖牛肉', '蚝油牛肉', '水煮牛肉', '小炒黄牛肉', '孜然牛肉', '洋葱炒牛肉', '牛肉面', '炒河粉', '罗宋汤'),
    "beef-brisket": ('西红柿牛腩',),
    "beef-steak": ('黑椒牛柳',),
    "beer": ('啤酒鸭',),
    "bighead-carp": ('鱼头豆腐汤',),
    "bitter-melon": ('苦瓜炒鸡蛋',),
    "black-pepper": ('黑椒牛柳', '煎荷包蛋', '炸鸡翅'),
    "black-tea": ('茶叶蛋',),
    "bread": ('三明治',),
    "broccoli": ('清炒西兰花', '蒜蓉西兰花', '干锅花菜', '西红柿炒菜花'),
    "butter": ('玉米浓汤', '蛋挞', '爆米花', '凤梨酥', '蛋黄酥'),
    "carrot": ('鱼香肉丝', '土豆炖肉', '土豆炖牛肉', '土豆炖鸡', '咖喱鸡', '家常豆腐', '凉拌三丝', '凉拌莴笋丝', '扬州炒饭', '炒面', '咖喱饭', '炒米粉', '玉米排骨汤', '罗宋汤', '春卷'),
    "celery": ('芹菜炒肉', '醋泡花生', '凉拌豆干'),
    "celtuce": ('清炒莴笋', '凉拌莴笋丝'),
    "century-egg": ('上汤娃娃菜', '皮蛋豆腐', '皮蛋瘦肉粥'),
    "chicken": ('白切鸡', '土豆炖鸡', '老母鸡汤'),
    "chicken-breast": ('宫保鸡丁',),
    "chicken-feet": ('泡椒凤爪',),
    "chicken-leg": ('辣子鸡', '黄焖鸡', '大盘鸡', '三杯鸡', '口水鸡', '香菇滑鸡', '咖喱鸡', '左宗棠鸡', '咖喱饭'),
    "chicken-wing": ('可乐鸡翅', '炸鸡翅'),
    "chili-pepper": ('蒜泥白肉', '小炒黄牛肉', '口水鸡', '凉拌海带丝', '凉拌豆干', '酸辣粉', '凉皮'),
    "chinese-yam": ('山药排骨汤',),
    "chives": ('韭菜炒鸡蛋', '炒豆芽', '饺子'),
    "cilantro": ('牛肉面', '酸辣粉'),
    "coconut": ('糯米糍',),
    "cooking-wine": ('红烧肉', '红烧鱼', '红烧带鱼'),
    "corn": ('煮玉米', '玉米排骨汤', '玉米浓汤', '爆米花'),
    "crab": ('香辣蟹',),
    "crucian-carp": ('红烧鱼',),
    "cucumber": ('黄瓜炒鸡蛋', '木须肉', '凉拌黄瓜', '凉拌三丝', '凉拌粉丝', '凉拌腐竹', '蒜泥黄瓜', '炸酱面', '凉皮'),
    "cumin": ('孜然牛肉', '孜然羊肉'),
    "curry-powder": ('咖喱鸡', '咖喱饭'),
    "daikon-radish": ('白萝卜炖羊肉', '酸萝卜老鸭汤', '牛肉面'),
    "doubanjiang": ('回锅肉', '鱼香肉丝', '肉末豆腐', '蚂蚁上树', '麻婆豆腐', '鱼香茄子'),
    "dried-chili": ('水煮牛肉', '宫保鸡丁', '辣子鸡', '左宗棠鸡', '酸菜鱼', '水煮鱼', '烤鱼', '香辣蟹', '手撕包菜', '醋溜白菜', '干煸四季豆', '醋溜土豆丝', '干锅花菜'),
    "dried-red-date": ('小米粥', '老母鸡汤', '银耳莲子汤'),
    "dried-tofu": ('香干炒肉', '凉拌豆干'),
    "duck": ('啤酒鸭', '酸萝卜老鸭汤', '盐水鸭'),
    "duck-blood": ('鸭血粉丝汤',),
    "duck-gizzard": ('鸭血粉丝汤',),
    "dumpling-wrapper": ('饺子', '锅贴', '煎饺'),
    "egg": ('西红柿炒鸡蛋', '韭菜炒鸡蛋', '洋葱炒鸡蛋', '苦瓜炒鸡蛋', '黄瓜炒鸡蛋', '木耳炒鸡蛋', '青椒炒鸡蛋', '蒸蛋羹', '虎皮鸡蛋', '木须肉', '狮子头', '虾仁炒蛋', '西葫芦炒蛋', '蛋炒饭', '扬州炒饭', '番茄鸡蛋面', '手抓饼', '煲仔饭', '卤肉饭', '三明治', '茶叶蛋', '煎荷包蛋', '紫菜蛋花汤', '西红柿鸡蛋汤', '酸辣汤', '番茄汤', '紫菜汤', '炸鸡翅', '麻花', '蛋挞', '凤梨酥', '布丁'),
    "eggplant": ('肉末茄子', '地三鲜', '红烧茄子', '鱼香茄子', '蒜泥茄子'),
    "enoki-mushroom": ('菌菇汤',),
    "garlic": ('青椒炒肉丝', '蒜泥白肉', '肉末茄子', '小炒黄牛肉', '辣子鸡', '蒜蓉粉丝虾', '香辣蟹', '蒜蓉扇贝', '爆炒鱿鱼', '清炒西兰花', '蒜蓉西兰花', '手撕包菜', '干煸四季豆', '地三鲜', '红烧茄子', '鱼香茄子', '蒜泥茄子', '清炒荷兰豆', '清炒油麦菜', '蒜蓉菠菜', '清炒空心菜', '干锅花菜', '清炒藕片', '蚝油生菜', '清炒丝瓜', '炒豆芽', '清炒莴笋', '清炒芦笋', '炒南瓜', '凉拌黄瓜', '凉拌木耳', '凉拌海带丝', '凉拌粉丝', '凉拌腐竹', '蒜泥黄瓜', '凉皮'),
    "garlic-sprout": ('回锅肉', '蒜薹炒肉'),
    "ginger": ('红烧肉', '红烧排骨', '白萝卜炖羊肉', '三杯鸡', '可乐鸡翅', '白切鸡', '香菇滑鸡', '啤酒鸭', '酸萝卜老鸭汤', '盐水鸭', '清蒸鲈鱼', '红烧鱼', '鱼头豆腐汤', '番茄鱼', '香煎带鱼', '红烧带鱼', '清蒸鲳鱼', '白灼虾', '蛤蜊汤', '冬瓜排骨汤', '玉米排骨汤', '莲藕排骨汤', '山药排骨汤', '老母鸡汤'),
    "glass-noodles": ('蚂蚁上树', '鸭血粉丝汤', '蒜蓉粉丝虾', '蒜蓉扇贝', '凉拌三丝', '凉拌粉丝'),
    "glutinous-rice": ('粽子',),
    "glutinous-rice-flour": ('南瓜饼', '糯米糍', '汤圆'),
    "grass-carp": ('糖醋鱼', '水煮鱼', '烤鱼'),
    "green-beans": ('干煸四季豆', '扬州炒饭'),
    "green-pepper": ('青椒炒鸡蛋', '回锅肉', '青椒炒肉丝', '鱼香肉丝', '蚝油牛肉', '黄焖鸡', '大盘鸡', '爆炒鱿鱼', '家常豆腐', '香干炒肉', '地三鲜', '炒土豆丝', '凉拌木耳'),
    "ground-pork": ('肉末茄子', '肉末豆腐', '蚂蚁上树', '狮子头', '麻婆豆腐', '酿豆腐', '干煸四季豆', '鱼香茄子', '炸酱面', '饺子', '包子', '馄饨', '锅贴', '煎饺'),
    "hairtail-fish": ('香煎带鱼', '红烧带鱼'),
    "ham": ('蛋炒饭', '扬州炒饭', '手抓饼', '三明治'),
    "hawthorn": ('糖葫芦',),
    "honey": ('龟苓膏',),
    "kelp": ('凉拌海带丝',),
    "kimchi": ('酸菜鱼', '泡椒凤爪'),
    "lamb": ('葱爆羊肉', '孜然羊肉', '白萝卜炖羊肉'),
    "lard": ('阳春面',),
    "leaf-lettuce": ('清炒油麦菜',),
    "lettuce": ('蚝油生菜', '手抓饼', '三明治'),
    "light-cream": ('南瓜汤', '冰淇淋'),
    "light-soy-sauce": ('白灼虾',),
    "littleneck-clam": ('蛤蜊汤',),
    "loofah": ('清炒丝瓜',),
    "lotus-root": ('清炒藕片', '莲藕排骨汤'),
    "lotus-seed": ('银耳莲子汤',),
    "milk": ('牛奶麦片', '南瓜汤', '玉米浓汤', '蛋挞', '冰淇淋', '布丁'),
    "millet": ('小米粥',),
    "miso": ('味噌汤',),
    "mung-bean": ('绿豆汤', '绿豆糕'),
    "mung-bean-sprouts": ('炒豆芽',),
    "napa-cabbage": ('猪肉炖粉条', '白菜炖粉条', '手撕包菜', '醋溜白菜', '炒面', '饺子', '包子', '炒米粉', '春卷', '锅贴', '煎饺'),
    "noodles": ('大盘鸡', '番茄鸡蛋面', '炸酱面', '葱油拌面', '阳春面', '炒面', '牛肉面'),
    "nori": ('馄饨', '紫菜蛋花汤', '味噌汤', '紫菜汤'),
    "oats": ('牛奶麦片',),
    "onion": ('洋葱炒鸡蛋', '西红柿牛腩', '黑椒牛柳', '孜然牛肉', '洋葱炒牛肉', '孜然羊肉', '咖喱鸡', '烤鱼', '爆炒鱿鱼', '炒河粉', '罗宋汤', '番茄汤'),
    "oyster-mushroom": ('菌菇汤',),
    "oyster-sauce": ('蚝油牛肉', '香菇滑鸡', '红烧豆腐', '蚝油生菜', '香菇青菜'),
    "peanut": ('宫保鸡丁', '口水鸡', '醋泡花生', '酸辣粉', '螺蛳粉'),
    "peeled-shrimp": ('虾仁炒蛋', '扬州炒饭'),
    "pickled-cabbage": ('酸萝卜老鸭汤', '酸菜鱼', '螺蛳粉'),
    "pickled-long-beans": ('螺蛳粉',),
    "pineapple": ('凤梨酥',),
    "pomfret": ('清蒸鲳鱼',),
    "pork": ('木须肉', '青椒炒肉丝', '鱼香肉丝', '白菜炖粉条', '芹菜炒肉', '蒜薹炒肉', '香干炒肉', '炒面', '炒米粉', '皮蛋瘦肉粥', '春卷'),
    "pork-belly": ('红烧肉', '回锅肉', '梅菜扣肉', '蒜泥白肉', '粉蒸肉', '猪肉炖粉条', '土豆炖肉', '腐竹烧肉', '干锅花菜', '卤肉饭', '粽子'),
    "pork-ribs": ('红烧排骨', '糖醋排骨', '冬瓜排骨汤', '玉米排骨汤', '莲藕排骨汤', '山药排骨汤'),
    "pork-tenderloin": ('糖醋里脊', '京酱肉丝'),
    "potato": ('土豆炖肉', '土豆炖牛肉', '黄焖鸡', '大盘鸡', '土豆炖鸡', '咖喱鸡', '烤鱼', '地三鲜', '炒土豆丝', '醋溜土豆丝', '咖喱饭', '罗宋汤'),
    "potherb-mustard": ('梅菜扣肉',),
    "pumpkin": ('炒南瓜', '小米粥', '南瓜汤', '南瓜饼'),
    "red-bean": ('糯米糍', '蛋黄酥', '芋圆'),
    "rice": ('粉蒸肉', '蛋炒饭', '扬州炒饭', '煲仔饭', '咖喱饭', '卤肉饭', '皮蛋瘦肉粥', '白粥'),
    "rice-noodle-sheet": ('炒河粉',),
    "rice-noodles": ('炒米粉', '螺蛳粉'),
    "rock-sugar": ('虎皮鸡蛋', '红烧肉', '红烧排骨', '银耳莲子汤', '糖葫芦'),
    "salt": ('椒盐虾', '葱油饼', '煎荷包蛋'),
    "salted-duck-egg": ('蛋黄酥',),
    "sausage": ('煲仔饭',),
    "scallion": ('京酱肉丝', '葱爆羊肉', '宫保鸡丁', '清蒸鲈鱼', '清蒸鲳鱼'),
    "scallop": ('蒜蓉扇贝',),
    "sea-bass": ('清蒸鲈鱼',),
    "seasoning": ('蒸蛋羹', '糖醋里脊', '三杯鸡', '左宗棠鸡', '糖醋鱼', '油焖大虾', '蒜泥茄子', '凉拌黄瓜', '皮蛋豆腐', '凉拌三丝', '凉拌莴笋丝', '葱油拌面'),
    "shanghai-green": ('香菇青菜', '煲仔饭'),
    "shiitake-mushroom": ('黄焖鸡', '香菇滑鸡', '香菇青菜', '炒米粉', '菌菇汤'),
    "shrimp": ('白灼虾', '油焖大虾', '蒜蓉粉丝虾', '椒盐虾'),
    "sichuan-peppercorn": ('水煮牛肉', '宫保鸡丁', '辣子鸡', '盐水鸭', '水煮鱼', '椒盐虾', '香辣蟹', '麻婆豆腐', '泡椒凤爪'),
    "snakehead-fish": ('酸菜鱼', '番茄鱼'),
    "snow-peas": ('清炒荷兰豆',),
    "soft-drink": ('可乐鸡翅',),
    "soy-sauce": ('虎皮鸡蛋', '梅菜扣肉', '红烧排骨', '红烧鱼', '红烧带鱼', '腐竹烧肉', '红烧茄子', '葱油拌面', '阳春面', '卤肉饭', '茶叶蛋'),
    "soybean": ('豆浆油条',),
    "soybean-paste": ('炸酱面',),
    "soybean-sprouts": ('水煮牛肉', '水煮鱼', '炸酱面', '炒河粉'),
    "spinach": ('蒜蓉菠菜',),
    "spring-onion": ('西红柿炒鸡蛋', '蒸蛋羹', '肉末茄子', '肉末豆腐', '蚂蚁上树', '白切鸡', '口水鸡', '鸭血粉丝汤', '鱼头豆腐汤', '蒜蓉粉丝虾', '虾仁炒蛋', '蒜蓉扇贝', '蛤蜊汤', '麻婆豆腐', '红烧豆腐', '酿豆腐', '清炒藕片', '皮蛋豆腐', '蛋炒饭', '番茄鸡蛋面', '葱油拌面', '阳春面', '葱油饼', '花卷', '炒河粉', '皮蛋瘦肉粥', '紫菜蛋花汤', '西红柿鸡蛋汤', '冬瓜排骨汤', '味噌汤'),
    "spring-roll-wrapper": ('春卷',),
    "squid": ('爆炒鱿鱼',),
    "star-anise": ('红烧肉', '啤酒鸭', '茶叶蛋'),
    "starch-noodles": ('猪肉炖粉条', '白菜炖粉条'),
    "sweet-bean-sauce": ('京酱肉丝',),
    "sweet-potato": ('粉蒸肉', '蒸红薯', '红薯饼'),
    "sweet-potato-noodles": ('酸辣粉',),
    "tapioca-starch": ('芋圆',),
    "taro": ('芋圆',),
    "tofu": ('肉末豆腐', '鱼头豆腐汤', '麻婆豆腐', '家常豆腐', '红烧豆腐', '酿豆腐', '皮蛋豆腐', '酸辣汤', '味噌汤'),
    "tofu-skin": ('腐竹烧肉', '凉拌腐竹', '螺蛳粉'),
    "tomato": ('西红柿炒鸡蛋', '西红柿牛腩', '番茄鱼', '西红柿炒菜花', '番茄鸡蛋面', '三明治', '西红柿鸡蛋汤', '罗宋汤', '番茄汤'),
    "vinegar": ('糖醋里脊', '糖醋排骨', '醋溜白菜', '炒土豆丝', '醋溜土豆丝', '凉拌黄瓜', '凉拌木耳', '凉拌海带丝', '凉拌三丝', '凉拌粉丝', '凉拌腐竹', '醋泡花生', '凉拌莴笋丝', '蒜泥黄瓜', '凉拌豆干', '酸辣粉', '凉皮', '酸辣汤'),
    "water-chestnut": ('狮子头',),
    "water-spinach": ('清炒空心菜',),
    "wheat-flour": ('香煎带鱼', '包子', '手抓饼', '葱油饼', '馒头', '花卷', '凉皮', '豆浆油条', '玉米浓汤', '炸鸡翅', '红薯饼', '麻花', '蛋挞', '凤梨酥', '蛋黄酥'),
    "white-fungus": ('银耳莲子汤',),
    "white-pepper": ('酸辣汤',),
    "white-sugar": ('糖醋里脊', '糖醋排骨', '糖醋鱼', '油焖大虾', '红烧茄子', '绿豆汤', '南瓜饼', '红薯饼', '汤圆', '麻花', '绿豆糕', '冰淇淋', '布丁'),
    "winter-melon": ('冬瓜排骨汤',),
    "wonton-wrapper": ('馄饨',),
    "wood-ear-fungus": ('木耳炒鸡蛋', '木须肉', '鱼香肉丝', '家常豆腐', '凉拌木耳', '酸辣汤'),
    "yeast": ('包子', '馒头', '花卷'),
    "zucchini": ('西葫芦炒蛋',),
}

# 全部菜名，按 CSV 顺序。
ALL_DISHES: tuple[str, ...] = tuple(DISH_NAMES)
